name = "notifly"
main = "src/index.ts"
compatibility_date = "2026-05-18"

[[kv_namespaces]]
binding = "NOTIFLY_KV"
id = "9b073deef38843f28db81dab09e5da15"
preview_id = "9b64a65f555d428aa5b21e1d7305b891"

[vars]
ANDROID_PACKAGE_NAME = "net.extrawdw.notifly"
DEFAULT_FCM_PRIORITY = "HIGH"

[triggers]
crons = ["0 3 * * *"]
